# Generated by Django 5.0.7 on 2024-09-12 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infopedia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='Creator responsible for the provided object. This field links to the user who created or is managing this object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='Creator responsible for the provided object. This field links to the user who created or is managing this object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Xxx.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='infopedia.categorymodel', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='choicemodel',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='Creator responsible for the provided object. This field links to the user who created or is managing this object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='Creator responsible for the provided object. This field links to the user who created or is managing this object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
    ]
