# Generated by Django 5.0.8 on 2024-08-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('pl', 'Polish')], default='en', help_text='Xxx.', max_length=2, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='choicemodel',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('pl', 'Polish')], default='en', help_text='Xxx.', max_length=2, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='tagmodel',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('pl', 'Polish')], default='en', help_text='Xxx.', max_length=2, verbose_name='Language'),
        ),
    ]
