# Generated by Django 5.0.8 on 2024-08-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infopedia', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='author',
        ),
    ]
