# Generated by Django 5.0.8 on 2024-08-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infopedia', '0002_categorymodel_language_choicemodel_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='language',
        ),
        migrations.RemoveField(
            model_name='choicemodel',
            name='language',
        ),
        migrations.RemoveField(
            model_name='tagmodel',
            name='language',
        ),
    ]
