# Generated by Django 5.0.8 on 2024-08-15 21:04

import wanderswiss.base.validators.base_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopedia', '0003_remove_categorymodel_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='content_de',
            field=models.TextField(help_text='Xxx.', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='content_en',
            field=models.TextField(help_text='Xxx.', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='content_pl',
            field=models.TextField(help_text='Xxx.', null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='name_de',
            field=models.CharField(error_messages={'invalid': 'Enter a valid name. It must contain 3 to 64 digits, letters, or special characters -, _ or spaces.'}, help_text='Unique name for the object. Must be between 3 and 64 characters long, and can include letters, digits, spaces, or special characters such as -, _.', max_length=64, null=True, validators=[wanderswiss.base.validators.base_validator.NameValueValidator()], verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='name_en',
            field=models.CharField(error_messages={'invalid': 'Enter a valid name. It must contain 3 to 64 digits, letters, or special characters -, _ or spaces.'}, help_text='Unique name for the object. Must be between 3 and 64 characters long, and can include letters, digits, spaces, or special characters such as -, _.', max_length=64, null=True, validators=[wanderswiss.base.validators.base_validator.NameValueValidator()], verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='name_pl',
            field=models.CharField(error_messages={'invalid': 'Enter a valid name. It must contain 3 to 64 digits, letters, or special characters -, _ or spaces.'}, help_text='Unique name for the object. Must be between 3 and 64 characters long, and can include letters, digits, spaces, or special characters such as -, _.', max_length=64, null=True, validators=[wanderswiss.base.validators.base_validator.NameValueValidator()], verbose_name='Name'),
        ),
    ]
