# Generated by Django 5.0.7 on 2024-08-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopedia', '0003_remove_articlemodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='state',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='hits',
            field=models.IntegerField(default=0, help_text='Xxx.', verbose_name='Xxx'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('pl', 'Polish')], default='en', help_text='Xxx.', max_length=2, verbose_name='Xxx'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Published'), (2, 'Draft')], default=2, help_text='Xxx.', verbose_name='Xxx'),
        ),
    ]
