# Generated by Django 5.0.7 on 2024-08-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopedia', '0005_tagmodel_alter_articlemodel_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='introtext',
            field=models.TextField(blank=True, help_text='Xxx.', null=True, verbose_name='Content'),
        ),
    ]
