# Generated by Django 5.0.7 on 2024-09-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementmodel',
            name='ico',
            field=models.CharField(choices=[('fa-regular fa-user', 'Administrator'), ('bi bi-1-circle', 'Circle')], default='fa-regular fa-user', help_text='Graphical representation of the object. Default value is Administrator icon.', max_length=64, verbose_name='Object ico'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='ico',
            field=models.CharField(choices=[('fa-regular fa-user', 'Administrator'), ('bi bi-1-circle', 'Circle')], default='fa-regular fa-user', help_text='Graphical representation of the object. Default value is Administrator icon.', max_length=64, verbose_name='Object ico'),
        ),
        migrations.AlterField(
            model_name='statisticmodel',
            name='ico',
            field=models.CharField(choices=[('fa-regular fa-user', 'Administrator'), ('bi bi-1-circle', 'Circle')], default='fa-regular fa-user', help_text='Graphical representation of the object. Default value is Administrator icon.', max_length=64, verbose_name='Object ico'),
        ),
    ]
