# Generated by Django 5.0.7 on 2024-09-12 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achievement', '0001_initial'),
        ('infopedia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementmodel',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='Creator responsible for the provided object. This field links to the user who created or is managing this object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='achievementmodel',
            name='difficulty',
            field=models.ForeignKey(help_text='Difficulty level of the achievement.', limit_choices_to={'type': 1}, on_delete=django.db.models.deletion.PROTECT, related_name='achievement_difficulty', to='infopedia.choicemodel', verbose_name='Difficulty'),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='countries',
            field=models.ManyToManyField(help_text='Countries through which the route passes.', limit_choices_to={'type': 5}, related_name='%(class)s_countries', to='infopedia.choicemodel', verbose_name='Countries'),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='Creator responsible for the provided object. This field links to the user who created or is managing this object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='difficulties',
            field=models.ManyToManyField(help_text='Xxx.', limit_choices_to={'type': 2}, related_name='card_difficulties', to='infopedia.choicemodel', verbose_name='Difficulties'),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='regions',
            field=models.ManyToManyField(help_text='Regions through which the route passes.', limit_choices_to={'type': 6}, related_name='%(class)s_regions', to='infopedia.choicemodel', verbose_name='Regions'),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='type',
            field=models.ForeignKey(help_text='Xxx.', limit_choices_to={'type': 4}, on_delete=django.db.models.deletion.PROTECT, related_name='card_type', to='infopedia.choicemodel', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='statisticmodel',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='Creator responsible for the provided object. This field links to the user who created or is managing this object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
    ]
