# Generated by Django 5.0.7 on 2024-08-16 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='surname',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='User first name.', max_length=128, unique=True, verbose_name='First name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='User last name.', max_length=128, unique=True, verbose_name='Last name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(help_text='The unique name of the administrator used for login and identification.', max_length=128, unique=True, verbose_name='Username'),
        ),
    ]
