# Generated by Django 5.0.7 on 2024-09-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_usermodel_name_remove_usermodel_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.IntegerField(choices=[(1, 'Administrator'), (2, 'Author'), (3, 'Guest')], default=3, help_text='User role.', verbose_name='Role'),
        ),
    ]
