# Generated by Django 5.0.7 on 2024-08-12 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0001_initial'),
        ('infopedia', '0007_choicemodel_alter_articlemodel_introtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routemodel',
            name='end_point',
            field=models.ForeignKey(help_text='Ending point of the route.', limit_choices_to={'type': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='route_end', to='infopedia.choicemodel', verbose_name='End Point'),
        ),
        migrations.RemoveField(
            model_name='routemodel',
            name='regions',
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='start_point',
            field=models.ForeignKey(help_text='Starting point of the route.', limit_choices_to={'type': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='route_start', to='infopedia.choicemodel', verbose_name='Start Point'),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='regions',
            field=models.ManyToManyField(help_text='Region(s) through which the route passes.', limit_choices_to={'type': 1}, to='infopedia.choicemodel', verbose_name='Regions'),
        ),
    ]
