# Generated by Django 5.0.7 on 2024-09-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hiking', '0001_initial'),
        ('infopedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='countries',
            field=models.ManyToManyField(help_text='Countries through which the route passes.', limit_choices_to={'type': 5}, related_name='%(class)s_countries', to='infopedia.choicemodel', verbose_name='Countries'),
        ),
    ]
