# Generated by Django 5.0.7 on 2024-09-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiking', '0003_initial'),
        ('infopedia', '0003_alter_choicemodel_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multidaytrialtrialmodel',
            options={'verbose_name': 'Multi day trial & Trial relation', 'verbose_name_plural': 'Multi day trial & Trial relations'},
        ),
        migrations.AlterModelOptions(
            name='trialroutemodel',
            options={'verbose_name': 'Trial & Route relation', 'verbose_name_plural': 'Trial & Route relations'},
        ),
        migrations.AlterModelOptions(
            name='usereventmodel',
            options={'verbose_name': 'User & Event relation', 'verbose_name_plural': 'User & Event relations'},
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='gps_data',
            field=models.TextField(blank=True, help_text='GPS data in XML format.', null=True, verbose_name='GPS Data'),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='middle_points',
            field=models.ManyToManyField(blank=True, help_text='All middle points of the route.', limit_choices_to={'type': 3}, null=True, related_name='route_middle_points', to='infopedia.choicemodel', verbose_name='Middle points'),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='min_elevation',
            field=models.FloatField(blank=True, help_text='Minimum elevation in meters.', null=True, verbose_name='Minimum Elevation (m)'),
        ),
    ]
